name: QA DevOps Lab

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  full-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install

      - name: Run Postman tests
        run: npm run test:postman:ci

      - name: Cleanup any running servers
        run: |
          echo "Cleaning up any old Node processes..."
          kill $(lsof -t -i:3000 -i:3001) 2>/dev/null || true

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          PORT: 3002
        with:
          start: npm start
          wait-on: 'http://localhost:3002'
          wait-on-timeout: 120
          browser: chrome
          spec: tests/cypress/e2e/**/*.cy.js
