name: CI/CD QA DevOps Lab

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  api-tests:
    name: Run Postman tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: |
          nohup npm start &
          echo "Waiting for server..."
          for i in {1..30}; do
            nc -z localhost 3000 && echo "Server up!" && break
            sleep 2
          done
      - run: |
          npm install -g newman
          newman run tests/postman/collection.json

  ui-tests:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm install cypress --save-dev
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          spec: tests/cypress/e2e/**/*.cy.js
